version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: refapp-app
    container_name: refapp-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - refapp-network

  db:
    image: mysql:8.0
    container_name: refapp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: refapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"  
    networks:
      - refapp-network

networks:
  refapp-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
